data:
    root: '../InstituteData' # path to Image split folder - Train, Test, Validation
    preprocessing:
        resize: [384, 256]  # width, height
        # resize: [480, 640]
    augmentation:
        photometric:  # enables brightness change and other non - geometrical transformations mentioned below
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 30}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:  # enables geometrical transformations using homography matrix
            enable: true
            num: 1 # 100
            aggregation: 'sum'
            filter_counts: 0
            homographies:
                params:
                    translation: true
                    rotation: true
                    scaling: true
                    perspective: true
                    scaling_amplitude: 0.2 # min: 0 max: 1.0
                    perspective_amplitude_x: 0.3 # min: 0 max: 1.0
                    perspective_amplitude_y: 0.3 # min: 0 max: 1.0
                    allow_artifacts: true
                    patch_ratio: 0.85  # max size of the image to crop and transform. min: 0.5 max: 1 (no crop)
                    max_angle: 0.785 # max angle of rotation in rad
                    translation_overflow: 0.2 # max overflow of image outside boundary max: 1.0 (full image out of boundary)

model:
    batch_size: 1 # 32
    detection_threshold: 0.015 # 0.015 confidence threshold in case of Superpoint
    nms: 4
    descriptor_dist: 8
    epsilon: 5 # max distance between the pixels to be considered as true - see homography estimation metric

detector_weights: "weights/superpointv1_TLShomo1.pt" # weights of Superpoint - set this to false if not training with Superpoint
CAPS_weights: "CAPS_grayscale_weights/150000.pth"  # weights of CAPS



